services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/postgres
      JWT_SECRET: 9019fd0335fa9d8a97714daa246ebe09
      JWT_ALGORITHM: HS256
      CORS_ORIGINS: "*"
    ports:
      - "127.0.0.1:8001:80"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
